/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: ../sanity.schema.json
export type Cta = {
  label?: string
  href?: string
  style?: 'solid' | 'outline'
}

export type ServicesCta = {
  label?: string
  href?: string
  style?: 'solid' | 'outline'
}

export type WhyChooseCta = {
  label?: string
  href?: string
  style?: 'solid' | 'outline'
}

export type TestimonialReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'testimonial'
}

export type SanityImageAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
}

export type TestimonialsSection = {
  _type: 'testimonialsSection'
  badge?: Badge
  heading?: string
  testimonials?: Array<
    {
      _key: string
    } & TestimonialReference
  >
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
}

export type StatItemReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'statItem'
}

export type StatsSection = {
  _type: 'statsSection'
  heading?: string
  bodyText?: string
  stats?: Array<
    {
      _key: string
    } & StatItemReference
  >
}

export type WhyChooseSection = {
  _type: 'whyChooseSection'
  badge?: Badge
  heading?: string
  bodyText?: BlockContentTextOnly
  features?: Array<
    {
      _key: string
    } & Feature
  >
  cta?: WhyChooseCta
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
}

export type ServiceOverviewReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'serviceOverview'
}

export type ServicesListSection = {
  _type: 'servicesListSection'
  badge?: Badge
  heading?: string
  services?: Array<
    {
      _key: string
    } & ServiceOverviewReference
  >
  cta?: ServicesCta
}

export type HeroSection = {
  _type: 'heroSection'
  badge?: Badge
  headline: string
  subline?: string
  bodyText?: string
  cta?: Cta
  heroImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
}

export type Feature = {
  _type: 'feature'
  label?: string
  icon?: string
}

export type Badge = {
  _type: 'badge'
  text?: string
  dotColor?: 'orange' | 'green' | 'brown'
}

export type PageReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'page'
}

export type PostReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'post'
}

export type Link = {
  _type: 'link'
  linkType?: 'href' | 'page' | 'post'
  href?: string
  page?: PageReference
  post?: PostReference
  openInNewTab?: boolean
}

export type CallToAction = {
  _type: 'callToAction'
  eyebrow?: string
  heading: string
  body?: BlockContentTextOnly
  button?: Button
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  theme?: 'light' | 'dark'
  contentAlignment?: 'textFirst' | 'imageFirst'
}

export type InfoSection = {
  _type: 'infoSection'
  heading?: string
  subheading?: string
  content?: BlockContent
}

export type BlockContentTextOnly = Array<{
  children?: Array<{
    marks?: Array<string>
    text?: string
    _type: 'span'
    _key: string
  }>
  style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
  listItem?: 'bullet' | 'number'
  markDefs?: Array<{
    href?: string
    _type: 'link'
    _key: string
  }>
  level?: number
  _type: 'block'
  _key: string
}>

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
      listItem?: 'bullet' | 'number'
      markDefs?: Array<{
        linkType?: 'href' | 'page' | 'post'
        href?: string
        page?: PageReference
        post?: PostReference
        openInNewTab?: boolean
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }
  | {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
      _key: string
    }
>

export type Button = {
  _type: 'button'
  buttonText?: string
  link?: Link
}

export type ServiceOverview = {
  _id: string
  _type: 'serviceOverview'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  slug: Slug
  shortDescription?: string
  icon?: string
  order: number
}

export type Slug = {
  _type: 'slug'
  current: string
  source?: string
}

export type StatItem = {
  _id: string
  _type: 'statItem'
  _createdAt: string
  _updatedAt: string
  _rev: string
  number: string
  label: string
  accentColor?: 'orange' | 'green' | 'brown' | 'grey'
  order: number
}

export type Testimonial = {
  _id: string
  _type: 'testimonial'
  _createdAt: string
  _updatedAt: string
  _rev: string
  quote: string
  authorName: string
  authorLabel?: string
  rating?: number
}

export type Homepage = {
  _id: string
  _type: 'homepage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  hero?: HeroSection
  services?: ServicesListSection
  whyChoose?: WhyChooseSection
  stats?: StatsSection
  testimonials?: TestimonialsSection
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top: number
  bottom: number
  left: number
  right: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x: number
  y: number
  height: number
  width: number
}

export type Settings = {
  _id: string
  _type: 'settings'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  description?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: Array<{
      linkType?: 'href' | 'page' | 'post'
      href?: string
      page?: PageReference
      post?: PostReference
      openInNewTab?: boolean
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  ogImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    metadataBase?: string
    _type: 'image'
  }
  tagline?: string
  phone?: string
  email?: string
  address?: {
    street?: string
    city?: string
    state?: string
    zip?: string
  }
  socialLinks?: Array<{
    platform?: 'facebook' | 'instagram' | 'twitter' | 'youtube' | 'tiktok' | 'yelp' | 'google'
    url?: string
    _key: string
  }>
}

export type Page = {
  _id: string
  _type: 'page'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: string
  slug: Slug
  heading: string
  subheading?: string
  pageBuilder?: Array<
    | ({
        _key: string
      } & CallToAction)
    | ({
        _key: string
      } & InfoSection)
  >
}

export type PersonReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'person'
}

export type Post = {
  _id: string
  _type: 'post'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  slug: Slug
  content?: BlockContent
  excerpt?: string
  coverImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  date?: string
  author?: PersonReference
}

export type Person = {
  _id: string
  _type: 'person'
  _createdAt: string
  _updatedAt: string
  _rev: string
  firstName: string
  lastName: string
  picture: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
}

export type SanityAssistInstructionTask = {
  _type: 'sanity.assist.instructionTask'
  path?: string
  instructionKey?: string
  started?: string
  updated?: string
  info?: string
}

export type SanityAssistTaskStatus = {
  _type: 'sanity.assist.task.status'
  tasks?: Array<
    {
      _key: string
    } & SanityAssistInstructionTask
  >
}

export type SanityAssistSchemaTypeAnnotations = {
  _type: 'sanity.assist.schemaType.annotations'
  title?: string
  fields?: Array<
    {
      _key: string
    } & SanityAssistSchemaTypeField
  >
}

export type SanityAssistOutputType = {
  _type: 'sanity.assist.output.type'
  type?: string
}

export type SanityAssistOutputField = {
  _type: 'sanity.assist.output.field'
  path?: string
}

export type AssistInstructionContextReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'assist.instruction.context'
}

export type SanityAssistInstructionContext = {
  _type: 'sanity.assist.instruction.context'
  reference: AssistInstructionContextReference
}

export type AssistInstructionContext = {
  _id: string
  _type: 'assist.instruction.context'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  context?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: null
    level?: number
    _type: 'block'
    _key: string
  }>
}

export type SanityAssistInstructionUserInput = {
  _type: 'sanity.assist.instruction.userInput'
  message: string
  description?: string
}

export type SanityAssistInstructionPrompt = Array<{
  children?: Array<
    | {
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }
    | ({
        _key: string
      } & SanityAssistInstructionFieldRef)
    | ({
        _key: string
      } & SanityAssistInstructionContext)
    | ({
        _key: string
      } & SanityAssistInstructionUserInput)
  >
  style?: 'normal'
  listItem?: never
  markDefs?: null
  level?: number
  _type: 'block'
  _key: string
}>

export type SanityAssistInstructionFieldRef = {
  _type: 'sanity.assist.instruction.fieldRef'
  path?: string
}

export type SanityAssistInstruction = {
  _type: 'sanity.assist.instruction'
  prompt?: SanityAssistInstructionPrompt
  icon?: string
  title?: string
  userId?: string
  createdById?: string
  output?: Array<
    | ({
        _key: string
      } & SanityAssistOutputField)
    | ({
        _key: string
      } & SanityAssistOutputType)
  >
}

export type SanityAssistSchemaTypeField = {
  _type: 'sanity.assist.schemaType.field'
  path?: string
  instructions?: Array<
    {
      _key: string
    } & SanityAssistInstruction
  >
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height: number
  width: number
  aspectRatio: number
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | Cta
  | ServicesCta
  | WhyChooseCta
  | TestimonialReference
  | SanityImageAssetReference
  | TestimonialsSection
  | StatItemReference
  | StatsSection
  | WhyChooseSection
  | ServiceOverviewReference
  | ServicesListSection
  | HeroSection
  | Feature
  | Badge
  | PageReference
  | PostReference
  | Link
  | CallToAction
  | InfoSection
  | BlockContentTextOnly
  | BlockContent
  | Button
  | ServiceOverview
  | Slug
  | StatItem
  | Testimonial
  | Homepage
  | SanityImageCrop
  | SanityImageHotspot
  | Settings
  | Page
  | PersonReference
  | Post
  | Person
  | SanityAssistInstructionTask
  | SanityAssistTaskStatus
  | SanityAssistSchemaTypeAnnotations
  | SanityAssistOutputType
  | SanityAssistOutputField
  | AssistInstructionContextReference
  | SanityAssistInstructionContext
  | AssistInstructionContext
  | SanityAssistInstructionUserInput
  | SanityAssistInstructionPrompt
  | SanityAssistInstructionFieldRef
  | SanityAssistInstruction
  | SanityAssistSchemaTypeField
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint

export declare const internalGroqTypeReferenceTo: unique symbol

// Source: sanity/lib/queries.ts
// Variable: settingsQuery
// Query: *[_type == "settings"][0]
export type SettingsQueryResult = {
  _id: string
  _type: 'settings'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  description?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: Array<{
      linkType?: 'href' | 'page' | 'post'
      href?: string
      page?: PageReference
      post?: PostReference
      openInNewTab?: boolean
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  ogImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    metadataBase?: string
    _type: 'image'
  }
  tagline?: string
  phone?: string
  email?: string
  address?: {
    street?: string
    city?: string
    state?: string
    zip?: string
  }
  socialLinks?: Array<{
    platform?: 'facebook' | 'google' | 'instagram' | 'tiktok' | 'twitter' | 'yelp' | 'youtube'
    url?: string
    _key: string
  }>
} | null

// Source: sanity/lib/queries.ts
// Variable: getPageQuery
// Query: *[_type == 'page' && slug.current == $slug][0]{    _id,    _type,    name,    slug,    heading,    subheading,    "pageBuilder": pageBuilder[]{      ...,      _type == "callToAction" => {        ...,        button {          ...,            link {      ...,        _type == "link" => {    "page": page->slug.current,    "post": post->slug.current  }      }        }      },      _type == "infoSection" => {        content[]{          ...,          markDefs[]{            ...,              _type == "link" => {    "page": page->slug.current,    "post": post->slug.current  }          }        }      },    },  }
export type GetPageQueryResult = {
  _id: string
  _type: 'page'
  name: string
  slug: Slug
  heading: string
  subheading: string | null
  pageBuilder: Array<
    | {
        _key: string
        _type: 'callToAction'
        eyebrow?: string
        heading: string
        body?: BlockContentTextOnly
        button: {
          _type: 'button'
          buttonText?: string
          link: {
            _type: 'link'
            linkType?: 'href' | 'page' | 'post'
            href?: string
            page: string | null
            post: string | null
            openInNewTab?: boolean
          } | null
        } | null
        image?: {
          asset?: SanityImageAssetReference
          media?: unknown
          hotspot?: SanityImageHotspot
          crop?: SanityImageCrop
          _type: 'image'
        }
        theme?: 'dark' | 'light'
        contentAlignment?: 'imageFirst' | 'textFirst'
      }
    | {
        _key: string
        _type: 'infoSection'
        heading?: string
        subheading?: string
        content: Array<
          | {
              children?: Array<{
                marks?: Array<string>
                text?: string
                _type: 'span'
                _key: string
              }>
              style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal'
              listItem?: 'bullet' | 'number'
              markDefs: Array<{
                linkType?: 'href' | 'page' | 'post'
                href?: string
                page: string | null
                post: string | null
                openInNewTab?: boolean
                _type: 'link'
                _key: string
              }> | null
              level?: number
              _type: 'block'
              _key: string
            }
          | {
              asset?: SanityImageAssetReference
              media?: unknown
              hotspot?: SanityImageHotspot
              crop?: SanityImageCrop
              _type: 'image'
              _key: string
              markDefs: null
            }
        > | null
      }
  > | null
} | null

// Source: sanity/lib/queries.ts
// Variable: sitemapData
// Query: *[_type == "page" || _type == "post" && defined(slug.current)] | order(_type asc) {    "slug": slug.current,    _type,    _updatedAt,  }
export type SitemapDataResult = Array<
  | {
      slug: string
      _type: 'page'
      _updatedAt: string
    }
  | {
      slug: string
      _type: 'post'
      _updatedAt: string
    }
>

// Source: sanity/lib/queries.ts
// Variable: allPostsQuery
// Query: *[_type == "post" && defined(slug.current)] | order(date desc, _updatedAt desc) {      _id,  "status": select(_originalId in path("drafts.**") => "draft", "published"),  "title": coalesce(title, "Untitled"),  "slug": slug.current,  excerpt,  coverImage,  "date": coalesce(date, _updatedAt),  "author": author->{firstName, lastName, picture},  }
export type AllPostsQueryResult = Array<{
  _id: string
  status: 'draft' | 'published'
  title: string
  slug: string
  excerpt: string | null
  coverImage: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  } | null
  date: string
  author: {
    firstName: string
    lastName: string
    picture: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      _type: 'image'
    }
  } | null
}>

// Source: sanity/lib/queries.ts
// Variable: morePostsQuery
// Query: *[_type == "post" && _id != $skip && defined(slug.current)] | order(date desc, _updatedAt desc) [0...$limit] {      _id,  "status": select(_originalId in path("drafts.**") => "draft", "published"),  "title": coalesce(title, "Untitled"),  "slug": slug.current,  excerpt,  coverImage,  "date": coalesce(date, _updatedAt),  "author": author->{firstName, lastName, picture},  }
export type MorePostsQueryResult = Array<{
  _id: string
  status: 'draft' | 'published'
  title: string
  slug: string
  excerpt: string | null
  coverImage: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  } | null
  date: string
  author: {
    firstName: string
    lastName: string
    picture: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      _type: 'image'
    }
  } | null
}>

// Source: sanity/lib/queries.ts
// Variable: postQuery
// Query: *[_type == "post" && slug.current == $slug] [0] {    content[]{    ...,    markDefs[]{      ...,        _type == "link" => {    "page": page->slug.current,    "post": post->slug.current  }    }  },      _id,  "status": select(_originalId in path("drafts.**") => "draft", "published"),  "title": coalesce(title, "Untitled"),  "slug": slug.current,  excerpt,  coverImage,  "date": coalesce(date, _updatedAt),  "author": author->{firstName, lastName, picture},  }
export type PostQueryResult = {
  content: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal'
        listItem?: 'bullet' | 'number'
        markDefs: Array<{
          linkType?: 'href' | 'page' | 'post'
          href?: string
          page: string | null
          post: string | null
          openInNewTab?: boolean
          _type: 'link'
          _key: string
        }> | null
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        asset?: SanityImageAssetReference
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        _type: 'image'
        _key: string
        markDefs: null
      }
  > | null
  _id: string
  status: 'draft' | 'published'
  title: string
  slug: string
  excerpt: string | null
  coverImage: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  } | null
  date: string
  author: {
    firstName: string
    lastName: string
    picture: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      _type: 'image'
    }
  } | null
} | null

// Source: sanity/lib/queries.ts
// Variable: postPagesSlugs
// Query: *[_type == "post" && defined(slug.current)]  {"slug": slug.current}
export type PostPagesSlugsResult = Array<{
  slug: string
}>

// Source: sanity/lib/queries.ts
// Variable: pagesSlugs
// Query: *[_type == "page" && defined(slug.current)]  {"slug": slug.current}
export type PagesSlugsResult = Array<{
  slug: string
}>

// Source: sanity/lib/queries.ts
// Variable: homepageQuery
// Query: *[_type == "homepage"][0]{    _id,    _type,    hero {      badge,      headline,      subline,      bodyText,      cta,      heroImage {        ...,        asset->      }    },    services {      badge,      heading,      "servicesList": services[]->{        _id,        title,        "slug": slug.current,        shortDescription,        icon,        order      } | order(order asc),      cta    },    whyChoose {      badge,      heading,      bodyText,      features,      cta,      image {        ...,        asset->      }    },    stats {      heading,      bodyText,      "statsList": stats[]->{        _id,        number,        label,        accentColor,        order      } | order(order asc)    },    testimonials {      badge,      heading,      "testimonialsList": testimonials[]->{        _id,        quote,        authorName,        authorLabel,        rating      },      image {        ...,        asset->      }    }  }
export type HomepageQueryResult = {
  _id: string
  _type: 'homepage'
  hero: {
    badge: Badge | null
    headline: string
    subline: string | null
    bodyText: string | null
    cta: Cta | null
    heroImage: {
      asset: {
        _id: string
        _type: 'sanity.imageAsset'
        _createdAt: string
        _updatedAt: string
        _rev: string
        originalFilename?: string
        label?: string
        title?: string
        description?: string
        altText?: string
        sha1hash?: string
        extension?: string
        mimeType?: string
        size?: number
        assetId?: string
        uploadId?: string
        path?: string
        url?: string
        metadata?: SanityImageMetadata
        source?: SanityAssetSourceData
      } | null
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      _type: 'image'
    } | null
  } | null
  services: {
    badge: Badge | null
    heading: string | null
    servicesList: Array<{
      _id: string
      title: string
      slug: string
      shortDescription: string | null
      icon: string | null
      order: number
    }> | null
    cta: ServicesCta | null
  } | null
  whyChoose: {
    badge: Badge | null
    heading: string | null
    bodyText: BlockContentTextOnly | null
    features: Array<
      {
        _key: string
      } & Feature
    > | null
    cta: WhyChooseCta | null
    image: {
      asset: {
        _id: string
        _type: 'sanity.imageAsset'
        _createdAt: string
        _updatedAt: string
        _rev: string
        originalFilename?: string
        label?: string
        title?: string
        description?: string
        altText?: string
        sha1hash?: string
        extension?: string
        mimeType?: string
        size?: number
        assetId?: string
        uploadId?: string
        path?: string
        url?: string
        metadata?: SanityImageMetadata
        source?: SanityAssetSourceData
      } | null
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      _type: 'image'
    } | null
  } | null
  stats: {
    heading: string | null
    bodyText: string | null
    statsList: Array<{
      _id: string
      number: string
      label: string
      accentColor: 'brown' | 'green' | 'grey' | 'orange' | null
      order: number
    }> | null
  } | null
  testimonials: {
    badge: Badge | null
    heading: string | null
    testimonialsList: Array<{
      _id: string
      quote: string
      authorName: string
      authorLabel: string | null
      rating: number | null
    }> | null
    image: {
      asset: {
        _id: string
        _type: 'sanity.imageAsset'
        _createdAt: string
        _updatedAt: string
        _rev: string
        originalFilename?: string
        label?: string
        title?: string
        description?: string
        altText?: string
        sha1hash?: string
        extension?: string
        mimeType?: string
        size?: number
        assetId?: string
        uploadId?: string
        path?: string
        url?: string
        metadata?: SanityImageMetadata
        source?: SanityAssetSourceData
      } | null
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      _type: 'image'
    } | null
  } | null
} | null

// Query TypeMap
import '@sanity/client'
declare module '@sanity/client' {
  interface SanityQueries {
    '*[_type == "settings"][0]': SettingsQueryResult
    '\n  *[_type == \'page\' && slug.current == $slug][0]{\n    _id,\n    _type,\n    name,\n    slug,\n    heading,\n    subheading,\n    "pageBuilder": pageBuilder[]{\n      ...,\n      _type == "callToAction" => {\n        ...,\n        button {\n          ...,\n          \n  link {\n      ...,\n      \n  _type == "link" => {\n    "page": page->slug.current,\n    "post": post->slug.current\n  }\n\n      }\n\n        }\n      },\n      _type == "infoSection" => {\n        content[]{\n          ...,\n          markDefs[]{\n            ...,\n            \n  _type == "link" => {\n    "page": page->slug.current,\n    "post": post->slug.current\n  }\n\n          }\n        }\n      },\n    },\n  }\n': GetPageQueryResult
    '\n  *[_type == "page" || _type == "post" && defined(slug.current)] | order(_type asc) {\n    "slug": slug.current,\n    _type,\n    _updatedAt,\n  }\n': SitemapDataResult
    '\n  *[_type == "post" && defined(slug.current)] | order(date desc, _updatedAt desc) {\n    \n  _id,\n  "status": select(_originalId in path("drafts.**") => "draft", "published"),\n  "title": coalesce(title, "Untitled"),\n  "slug": slug.current,\n  excerpt,\n  coverImage,\n  "date": coalesce(date, _updatedAt),\n  "author": author->{firstName, lastName, picture},\n\n  }\n': AllPostsQueryResult
    '\n  *[_type == "post" && _id != $skip && defined(slug.current)] | order(date desc, _updatedAt desc) [0...$limit] {\n    \n  _id,\n  "status": select(_originalId in path("drafts.**") => "draft", "published"),\n  "title": coalesce(title, "Untitled"),\n  "slug": slug.current,\n  excerpt,\n  coverImage,\n  "date": coalesce(date, _updatedAt),\n  "author": author->{firstName, lastName, picture},\n\n  }\n': MorePostsQueryResult
    '\n  *[_type == "post" && slug.current == $slug] [0] {\n    content[]{\n    ...,\n    markDefs[]{\n      ...,\n      \n  _type == "link" => {\n    "page": page->slug.current,\n    "post": post->slug.current\n  }\n\n    }\n  },\n    \n  _id,\n  "status": select(_originalId in path("drafts.**") => "draft", "published"),\n  "title": coalesce(title, "Untitled"),\n  "slug": slug.current,\n  excerpt,\n  coverImage,\n  "date": coalesce(date, _updatedAt),\n  "author": author->{firstName, lastName, picture},\n\n  }\n': PostQueryResult
    '\n  *[_type == "post" && defined(slug.current)]\n  {"slug": slug.current}\n': PostPagesSlugsResult
    '\n  *[_type == "page" && defined(slug.current)]\n  {"slug": slug.current}\n': PagesSlugsResult
    '\n  *[_type == "homepage"][0]{\n    _id,\n    _type,\n    hero {\n      badge,\n      headline,\n      subline,\n      bodyText,\n      cta,\n      heroImage {\n        ...,\n        asset->\n      }\n    },\n    services {\n      badge,\n      heading,\n      "servicesList": services[]->{\n        _id,\n        title,\n        "slug": slug.current,\n        shortDescription,\n        icon,\n        order\n      } | order(order asc),\n      cta\n    },\n    whyChoose {\n      badge,\n      heading,\n      bodyText,\n      features,\n      cta,\n      image {\n        ...,\n        asset->\n      }\n    },\n    stats {\n      heading,\n      bodyText,\n      "statsList": stats[]->{\n        _id,\n        number,\n        label,\n        accentColor,\n        order\n      } | order(order asc)\n    },\n    testimonials {\n      badge,\n      heading,\n      "testimonialsList": testimonials[]->{\n        _id,\n        quote,\n        authorName,\n        authorLabel,\n        rating\n      },\n      image {\n        ...,\n        asset->\n      }\n    }\n  }\n': HomepageQueryResult
  }
}
